name: Build Images

on:
  push:
    branches: 
      - master
      - devel
  pull_request:
      paths:
        - docker-compose.yml
        - services

jobs:
  build:
    strategy:
      matrix:
        profile:
          - auto
          - sygil
          - invoke
          - download
    runs-on: ubuntu-latest
    name: ${{ matrix.profile }}
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: |
          REGISTRY_ID=ghcr.io/${{ github.repository_owner }}
          # Change all uppercase to lowercase
          REGISTRY_ID=$(echo $REGISTRY_ID | tr '[A-Z]' '[a-z]')
          echo REGISTRY_ID=$REGISTRY_ID

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest
          echo VERSION=$VERSION

          REGISTRY_ID=$REGISTRY_ID docker compose --profile ${{ matrix.profile }} build --progress plain

      - name: Log in to registry
        # This is where you will update the personal access token to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Push image
        run: |
          REGISTRY_ID=$REGISTRY_ID docker compose --profile ${{ matrix.profile }} push
          
